# Use uma imagem base do PHP com Apache
FROM php:8-apache


# Copie os arquivos do projeto para o contêiner
COPY . /var/www/html

# Configure as permissões corretas para o diretório de armazenamento do Laravel
RUN chown -R www-data:www-data /var/www/html/storage

# Instale as dependências do PHP
RUN apt-get update && \
    apt-get install -y \
        libzip-dev \
        zip \
        default-mysql-client \
        unzip && \
    docker-php-ext-install zip && \
    docker-php-ext-enable zip

# Configure o Apache para servir o Laravel
RUN a2enmod rewrite

# Instale as dependências do Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Execute o Composer para instalar as dependências
RUN composer install

COPY apache-config.conf /etc/apache2/conf-available/
RUN ln -s /etc/apache2/conf-available/apache-config.conf /etc/apache2/conf-enabled/

COPY apache-config.conf /etc/apache2/sites-available/000-default.conf
RUN docker-php-ext-install pdo_mysql


RUN chown -R www-data:www-data storage
RUN chown -R www-data:www-data bootstrap/cache

RUN php artisan cache:clear
RUN php artisan config:clear

# Defina a variável de ambiente APP_KEY do Laravel
RUN php artisan key:generate



# Exponha a porta 80 para acessar o aplicativo Laravel
EXPOSE 80

# Comando para iniciar o servidor Apache
CMD ["apache2-foreground"]